windows platform fixes [13947]
eProsima/Fast-DDS-python pull request #11
Opened 2022-03-01 10:21 UTC by MiguelBarro

+ swig files must ignore some non-exported APIs (unix exports everything by policy)
+ fix examples CMake framework to handle dlls exports
+ hinting workaround for python [importing issues](https://bugs.python.org/issue46276)

2022-03-11 09:49 UTC, MiguelCompany requested changes
Fix DCO and see my comments below

2022-03-11 09:49 UTC, MiguelCompany commented on .github/workflows/test.meta
> +                "-DSECURITY=ON",
Why adding security? I would do that on a follow-up if need be.

2022-03-11 09:49 UTC, MiguelCompany commented on fastdds_python/src/swig/fastdds/dds/core/condition/StatusCondition.i
> +%ignore eprosima::fastdds::dds::StatusCondition::StatusCondition;
Remove this file and move this to `Condition.i`

2022-03-11 09:49 UTC, MiguelCompany commented on fastdds_python/src/swig/fastdds/dds/subscriber/DataReader.i
> +
Remove this. The method is exported by Fast DDS now.

2022-03-11 09:49 UTC, MiguelCompany commented on fastdds_python/src/swig/fastdds/dds/topic/Topic.i
> +%ignore eprosima::fastdds::dds::Topic::get_inconsistent_topic_status;
I would add the export to Fast DDS and remove this line.

2022-03-11 11:29 UTC, MiguelCompany approved these changes
Just a question, but LGTM

2022-03-11 11:29 UTC, MiguelCompany commented on fastdds_python_examples/HelloWorldExample/HelloWorldExample.py
> +
Should we uncomment these lines?

2022-03-11 11:33 UTC, richiware commented on fastdds_python_examples/HelloWorldExample/HelloWorldExample.py
> +
Yes and uploaded.

2022-03-11 11:37 UTC, MiguelCompany submitted a review, later dismissed
LGTM

2022-03-15 10:49 UTC, EduPonz approved these changes

2022-03-15 10:50 UTC, merged