[21808] Update DataWriter/Reader `get_matched_publication/subscription...()` (2.x) API tests
eProsima/Fast-DDS-python pull request #188
Opened 2024-10-09 08:33 UTC by Mario-DL

## Description

This PR updates DataWriter/Reader `get_matched_publication/subscirption...()` tests in the `Fast DDS Python 2.x branch` as result of API implementation:

* eProsima/Fast-DDS#5312

## Contributor Checklist

- [X] Commit messages follow the project guidelines. 
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally
- **N/A** Changes are API compatible. 
- **N/A** Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-10-09 09:06 UTC, Mario-DL commented
IMO This PR should target a `2.1.x` branch

2024-10-09 09:10 UTC, Mario-DL commented
IMO this PR should target the minor attached to `Fast DDS 3.2.x`

2024-10-21 07:13 UTC, richiware requested changes

2024-10-21 07:13 UTC, richiware commented on fastdds_python/test/api/test_datareader.py
> +    assert(1 == ihs.size())
Check the instance_handle in the vector is the same that the datawriter.

2024-10-21 07:13 UTC, richiware commented on fastdds_python/test/api/test_datawriter.py
> +def test_get_matched_subscription_data(datawriter, reader_topic, subscriber):
why don't create a pytest fixture `datareader` that could be used in future tests?

2024-10-21 09:30 UTC, richiware approved these changes

2024-10-25 07:02 UTC, merged