Add python modules tests
eProsima/Fast-DDS-python pull request #54
Opened 2023-06-22 05:28 UTC by rsanchez15

2023-06-22 12:22 UTC, richiware requested changes

2023-06-22 12:22 UTC, richiware commented on fastdds_python/test/README.md
> +1.  Navigate to `fastdds_python/fastdds_python/test/types`
```suggestion
1.  Navigate to `fastdds_python/test/types`
```

2023-09-21 12:04 UTC, richiware requested changes

2023-09-21 12:04 UTC, richiware commented on fastdds_python/test/types/test_complete.idl
> +#include "test_included_modules.idl"
IDL generated source code should be regenerated with Fast DDS-Gen 3.0.0

2023-09-21 12:04 UTC, richiware commented on fastdds_python/test/types/test_modules.idl
> +module eprosima
IDL generated source code should be regenerated with Fast DDS-Gen 3.0.0

2023-10-02 08:05 UTC, EduPonz approved these changes

2023-10-02 08:06 UTC, merged