Support of optional members [19678]
eProsima/Fast-DDS-python pull request #66
Opened 2023-10-06 07:55 UTC by richiware

Also add support for collections of arrays.

Depends on:
- #65 
- eprosima/fastcdr#169

Related to:
- eprosima/fast-dds-gen#245

2023-10-17 10:49 UTC, JLBuenoLopez-eProsima requested changes

2023-10-17 10:49 UTC, JLBuenoLopez-eProsima commented on fastdds_python/test/types/CMakeLists.txt
I have checked that regenerating the files using Fast DDS-Gen branch `feature/optional` generates the same files as in this PR. This CMakeLists.txt file differs.

2023-10-24 06:27 UTC, JLBuenoLopez-eProsima commented on fastdds_python/test/types/CMakeLists.txt
Whereas the test types seem to have been regenerated with the `feature/optional` branch of Fast DDS-Gen, the types used in the example package does not seem to.

2023-10-24 06:39 UTC, richiware commented on fastdds_python/test/types/CMakeLists.txt
Done in cc32966

2023-10-24 07:02 UTC, JLBuenoLopez-eProsima approved these changes
LGTM

2023-10-24 07:04 UTC, merged